# Generated by Django 3.2.9 on 2021-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(default=False)),
                ('tpep_pickup_datetime', models.DateTimeField(default=False)),
                ('tpep_dropoff_datetime', models.DateTimeField(default=False)),
                ('passenger_count', models.FloatField(default=False)),
                ('trip_distance', models.FloatField(default=False)),
                ('ratecode_id', models.FloatField(default=False)),
                ('store_and_fwd_flag', models.CharField(max_length=1)),
                ('pulocation_id', models.IntegerField(default=False)),
                ('dolocation_id', models.IntegerField(default=False)),
                ('payment_type', models.FloatField(default=False)),
                ('fare_amount', models.FloatField(default=False)),
                ('extra', models.FloatField(default=False)),
                ('mta_tax', models.FloatField(default=False)),
                ('tip_amount', models.FloatField(default=False)),
                ('tolls_amount', models.FloatField(default=False)),
                ('improvement_surcharge', models.FloatField(default=False)),
                ('total_amount', models.FloatField(default=False)),
                ('congestion_surcharge', models.FloatField(default=False)),
            ],
            options={
                'db_table': 'nyc_taxi_data',
            },
        ),
    ]
